# Generated by Django 4.0.3 on 2023-11-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('capstone', '0010_alter_impromptuquiz_section_alter_surveyquiz_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('subjects', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.png', upload_to='profile/')),
            ],
        ),
    ]
