# Generated by Django 4.2.7 on 2023-11-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_usertopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquiz',
            name='topic',
            field=models.CharField(choices=[('개인주택이나 아파트에 홀로 거주', '개인주택이나 아파트에 홀로 거주'), ('가족과 함께 주택이나 아파트 거주', '가족과 함께 주택이나 아파트 거주'), ('영화보기', '영화보기'), ('공연보기', '공연보기'), ('공원가기', '공원가기'), ('해변가기', '해변가기'), ('카페/커피 전문점 가기', '카페/커피 전문점 가기'), ('쇼핑하기', '쇼핑하기'), ('TV시청하기', 'TV시청하기'), ('스포츠관람', '스포츠관람'), ('음악 감상하기', '음악 감상하기'), ('악기 연주하기', '악기 연주하기'), ('독서', '독서'), ('혼자 노래 부르거나 합창하기', '혼자 노래 부르거나 합창하기'), ('요리하기', '요리하기'), ('조깅', '조깅'), ('걷기', '걷기'), ('헬스', '헬스'), ('집에서 보내는 휴가', '집에서 보내는 휴가'), ('국내여행', '국내여행'), ('해외여행', '해외여행')], max_length=100),
        ),
    ]
