# Generated by Django 4.2.7 on 2023-11-23 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0014_remove_usertopic_survey_topic_usertopic_topic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertopic',
            unique_together={('user', 'topic')},
        ),
    ]
