# Generated by Django 4.2.7 on 2023-11-26 00:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0016_alter_usertopic_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTopic',
            new_name='SurveyTopicbyUser',
        ),
    ]
