# Generated by Django 4.2.7 on 2023-11-26 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0018_alter_impromptuquiz_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impromptuquiz',
            name='topic',
            field=models.CharField(choices=[('가구', '가구'), ('명절/휴일', '명절/휴일'), ('재활용', '재활용'), ('지형과 활동', '지형과 활동'), ('자유시간', '자유시간'), ('모임', '모임'), ('호텔', '호텔'), ('기술', '기술'), ('휴대폰', '휴대폰'), ('인터넷', '인터넷'), ('산업', '산업'), ('교통수단', '교통수단'), ('음식/음식점', '음식/음식점'), ('건강', '건강'), ('은행', '은행'), ('약속', '약속'), ('날씨', '날씨'), ('의상/패션', '의상/패션')], max_length=100),
        ),
        migrations.CreateModel(
            name='ImpromtuTopicbyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('가구', '가구'), ('명절/휴일', '명절/휴일'), ('재활용', '재활용'), ('지형과 활동', '지형과 활동'), ('자유시간', '자유시간'), ('모임', '모임'), ('호텔', '호텔'), ('기술', '기술'), ('휴대폰', '휴대폰'), ('인터넷', '인터넷'), ('산업', '산업'), ('교통수단', '교통수단'), ('음식/음식점', '음식/음식점'), ('건강', '건강'), ('은행', '은행'), ('약속', '약속'), ('날씨', '날씨'), ('의상/패션', '의상/패션')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
