# Generated by Django 4.2.7 on 2023-11-26 00:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capstone', '0019_alter_impromptuquiz_topic_impromtutopicbyuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImpromtuTopicbyUser',
            new_name='ImpromptuTopicbyUser',
        ),
    ]
