# Generated by Django 4.2.7 on 2023-12-07 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("capstone", "0020_rename_impromtutopicbyuser_impromptutopicbyuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("user_response", models.TextField()),
                ("corrected_response", models.TextField()),
                ("recording_time", models.CharField(max_length=255)),
                ("accuracy", models.FloatField()),
                ("similarity", models.FloatField()),
                (
                    "current_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
