# Generated by Django 4.2.7 on 2023-12-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0021_responsemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsemodel",
            name="current_date",
            field=models.CharField(max_length=255),
        ),
    ]
