# Generated by Django 4.2.7 on 2023-12-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0023_responsemodel_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedbackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField()),
                ("corrected_answer", models.TextField()),
            ],
        ),
    ]
